### ISSUE TITLE
Error while running the example

### ISSUE THREAD

**Issue by abhi18av** [zero-one-group/geni#125]
Hi Team,

Thanks for this wonderful project - I am really excited to see the integration with Spark 3!

I was trying out the latest `0.0.19` and ran into an import error while trying out the example

```clojure
Clojure 1.10.1
(ns spark.geni.core
  (:require
    [clojure.string]
    [zero-one.geni.core :as g]
    [zero-one.geni.ml :as ml]))


Syntax error (ClassNotFoundException) compiling at (zero_one\geni\interop.clj:1:1).
org.apache.spark.ml.linalg.DenseVector


```

Could you please help me out a bit here?

**Comment by abhi18av** [comment]
Here's my `project.clj`

```clojure
(defproject spark-clj "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "EPL-2.0 OR GPL-2.0-or-later WITH Classpath-exception-2.0"
            :url  "https://www.eclipse.org/legal/epl-2.0/"}
  :dependencies [[org.clojure/clojure "1.10.1"]
                           ;; spark
                          [zero.one/geni "0.0.19"]]
  :repl-options {:init-ns spark-clj.core})

```

**Comment by abhi18av** [comment]
Actually, I fixed it - the issue was because of incomplete config in `project.clj`. I added the `spark` packages and it started working fine.

**Comment by anthony-khong** [comment]
Hi @abhi18av, due to the size of the Spark packages, it's not included in Geni's clojars. It's probably easiest to use the Geni lein template: `lein new geni <project-name>` or, say, `lein new geni <project-name> +xgboost` if you want to do XGBoost.

**Comment by abhi18av** [comment]
Yeah, I realized that later. I restructured the project to that template itself - works great!
