### ISSUE TITLE
Can't specify schema when reading/writing dataframes

### ISSUE THREAD

**Issue by erp12** [zero-one-group/geni#190]
- [x] I have read through the quick start and installation sections of the [README](../README.md).

First, I have to thank you for creating this library! I have been using Geni for about a week now and it is great to have a Clojure interface into Spark dataframes.

It seems like the dataframe reading/writing API doesn't support specifying a schema. Looking at the library source code, it seems like most map entries fall back on the reader's/writer's `.option(key, val)` method. This works in any case where the option's value is a String, Boolean, Long, or Double because Spark has overloaded methods for this. 

In the case of schemas, we  must specify a StructType (or schema string) and thus Spark requires us to call the `.schema` method instead of `.option`. It would be great if geni could treat the `:schema` key of the reader/writer options as a special case and pass the value to `.schema` instead of `.option`.

See the code snippet below as an example.

## Info

| Info             | Value |
| ---              | ---   |
| Operating System | MacOS Catalina   |
| Geni Version     | 0.0.25  |
| JDK              | 1.8   |
| Spark Version    | 3.0   |

## Problem / Steps to reproduce

```clj
(require '[zero-one.geni.core :as g])

(g/read-csv! "test/resources/data/tiny_table.csv"
             {:header    true
              :delimiter ","
              :schema    (g/struct-type
                           (g/struct-field :i :long true)
                           (g/struct-field :s :string true))})
;; Execution error (IllegalArgumentException) at zero-one.geni.core.data-sources/configure-reader-or-writer$fn (data_sources.clj:19).
;; No matching method option found taking 2 args for class org.apache.spark.sql.DataFrameReader
```

**Comment by anthony-khong** [comment]
Hi @erp12 thank you for taking the time to write the issue!

I think it would also be nice to be able to say:

```clojure
{...
 :schema {:i :long :j :string}}
```

where it defaults to nillable struct fields. I think it makes sense to have it here and in `dataset-creation.clj`. I'm on it!

Please let us know if you've found any other rough edges! Every bit of contribution helps! Cheers!

**Comment by erp12** [comment]
I like your data oriented schema declaration!

Do you have a sense of what it would look like for complex column types? Perhaps:

```clj
{...
 :schema {:arr_of_long [:long] 
          :map_of_str_to_int [:string :int]
          :struct_about_person {:name :string
                                :age :int
                                :address :string}}
```

**Comment by anthony-khong** [comment]
Ah yes, I wasn't thinking about complex types. That looks good!

I think I'll split that into two PRs. One to support `:schema` + data-oriented schema for simple types, and another for the complex types. Hope to get it done this week, and ship it in the next release!

**Comment by anthony-khong** [comment]
Hi @erp12, check out the first PR for the simple data-oriented schema: https://github.com/zero-one-group/geni/pull/192/files#diff-f3c27b5a3ef884794ecffe47834e4703R15

I'm releasing every Wednesday, so this will be there for v0.0.26 and it should be up tomorrow. Hopefully I can squeeze in the complex data types by then!

**Comment by anthony-khong** [comment]
And the second PR for complex dtypes: https://github.com/zero-one-group/geni/pull/193/files#diff-f3c27b5a3ef884794ecffe47834e4703R15

If you are happy with those changes, would you be happy for me to close this issue?

**Comment by erp12** [comment]
Looks great! Thanks for rolling this out so quickly. :) I look forward to the next release.
