### ISSUE TITLE
Test failures when calling midje outside of dockerized CI

### ISSUE THREAD

**Issue by erp12** [zero-one-group/geni#210]
- [x] I have read through the quick start and installation sections of the [README](../README.md).

## Info

| Info             | Value |
| ---              | ---   |
| Operating System | macOS Catalina  |
| Geni Version     | 0.0.27   |
| JDK              | 1.8   |
| Spark Version    | 3.0.1   |

## Problem / Steps to reproduce

Today I had some time to sit down and get my fork setup for local development. It's been a while since I used lein and I am new to midje, so I apologize in advance if I ask stupid questions! While following CONTRIBUTING.md, I was able to run `make ci` with no problems after I allowed the MacOS docker client to see the default directory of temporary files. In case you want to add a note about in the documentation, I have pasted the initial error message below:

```
Successfully tagged zeroonetechnology/geni:latest
cp -r . /var/folders/zl/hlg5bvnj1y9753gvjsf0_86r0000gn/T/tmp.nV2X5lAq
docker run --rm -v /var/folders/zl/hlg5bvnj1y9753gvjsf0_86r0000gn/T/tmp.nV2X5lAq:/root/geni -w /root/geni -t zeroonetechnology/geni \
                scripts/coverage
docker: Error response from daemon: Mounts denied: 
The path /var/folders/zl/hlg5bvnj1y9753gvjsf0_86r0000gn/T/tmp.nV2X5lAq
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
```

The dockerized CI is great and easy to use, but I also attempted to use `lein midje` directly so that I could filter to facts and have a faster workflow. Is this recommended? I am getting 6 failed tests when running `lein midje`, but I know these failures are configuration differences on my machine, because the dockerized CI passes. If using midje directly is intended to be supported, then a few notes in the documentation should be added (or the tests tweaked).  

Attached to this issue is the saved stdout and stderr produce midje on the `develop` branch. I will summarize the issues I encountered below.

1. `(fact "On XGB native" :slow ...)` Raises and exception `XGBoostError: XGBoostModel training failed` and also bizarely causes a Clojure compilation error. The location of the compilation error is not the "On XBG native" fact, and yet when I comment out the fact the compilation error goes away. See [the full stack trace here](https://github.com/zero-one-group/geni/files/5256251/on-XGB-native.txt).

2. `On JavaSparkContext methods` checks `(rdd/spark-home) => nil?`. My development machine has a spark home set via environment, and thus `(rdd/spark-home)` is not nil. Why spark home be nil? Could this test be equally effective as  `(rdd/spark-home) => any?`.

3. The RDD saving and loading tests fail due to a file-not-found. I suspect the root cause of this issue is MacOS's way of handling temporary files. These errors can be resolved by using the `java.nio.file` temporary file utilities that should be useable cross platform. For example, these tests passed once I modified `create-temp-file!` to the following.

```
(def -tmp-dir-attr
  (into-array FileAttribute '()))

(defn create-temp-file! [extension]
  (let [temp-dir (.toFile (Files/createTempDirectory "tmp-dir" -tmp-dir-attr))]
    (File/createTempFile "temporary" extension temp-dir)))
```

4. There are 2 date/time failures in `sql_functions_test.clj` which are simply due to timezones. I was able to fix them by adding `:spark.sql.session.timeZone "UTC"` to the spark session configuration in `defaults.clj`, although I don't think that is a good permanent fix. 

I would recommend creating both the "actual" and "expected" dates from the same unix timestamp, but use Spark for "actual" and use `java.time` directly for the "expected". This way, both Spark and Java will be using the default timezone of the machine. For example:

```
(-> (Instant/ofEpochMilli 1)
    (.atZone (ZoneId/systemDefault))
    (.toLocalDate))
```

Stdout and Stderr output for 2 - 4 can be found here: 
[geni-test-results.txt](https://github.com/zero-one-group/geni/files/5256294/geni-test-results.txt)

**Comment by anthony-khong** [comment]
Wow, thank you so much @erp12 for raising this issue! This is exactly what the project needs to ensure a good, repeatable dev experience.

> It's been a while since I used lein and I am new to midje, so I apologize in advance if I ask stupid questions!

There's absolutely no stupid questions! We're very grateful that these issues are being raised!

> I was able to run make ci with no problems after I allowed the MacOS docker client to see the default directory of temporary files

I will need to add this to the contributing guide. What the Makefile does is to run copy the entire `geni` directory to a temporary directory and run the task there. This allows you to do something like `make ci --jobs 2` without multiple threads trying to write to the same `target` directory. Parallel runs are great because the coverage task is CPU bound and the install task is network bound. 

> The dockerized CI is great and easy to use, but I also attempted to use lein midje directly so that I could filter to facts and have a faster workflow. Is this recommended?

You can still do this inside Docker. Try `make repl` and run these [two lines](https://github.com/zero-one-group/geni/blob/develop/src/clojure/zero_one/geni/main.clj#L67), but changing the tag (e.g. from `:streaming` to a new tag of what you're working on). Then when you write the test, you can tag a group of midje facts like [this one](https://github.com/zero-one-group/geni/blob/develop/test/zero_one/geni/streaming_test.clj#L48). It'll just load those tags whenever you make a change. If you want to autotest everything, you can get rid of the filter and tag, and just run `(autotest)`. I will also add this to the CONTRIBUTING.md doc.

Having said that, straight up `lein midje` should **just work**, so I really want to get to the bottom of these issues that you mentioned. I will need to carefully replicate the failures and make the tests more robust - I'll incrementally update you on this issue as I work on it. I may need your help to do the failure replications!

**Comment by anthony-khong** [comment]
I just updated the CONTRIBUTING.md doc.

I wonder if the first issue on XGBoost is due to an undocumented Python + argparse dependency? Check out: https://github.com/dmlc/xgboost/issues/3824

Issues 2-4 seem to be straightforward! I'm happy to go with your recommendations! Would you like to make a PR for the patch? Otherwise, I'm happy to give it a shot tomorrow!

**Comment by erp12** [comment]
I'm glad to hear this is helpful! Your suggestion of `make repl` to run unit tests in the docker container interactively worked perfectly. Thanks for your help.

Also, I took a shot at resolving 2-4 in #213. 

As for the XGBoost issue, I think you are onto something with the undocumented Python dependancies. I will do some more reading in the next few days to see if I can figure out what is wrong. It is more than likely that the root cause exists between XGBoost and my machine and has nothing to do with Geni.

**Comment by anthony-khong** [comment]
Please let me know if you managed to fix it. If it's not documented in XGBoost4J, at least we should document it in Geni 👍

**Comment by anthony-khong** [comment]
Hi @erp12 have you had the chance to look into whether Python + argparse was the issue? 😁

**Comment by erp12** [comment]
I just discovered the fix fo this!

> Hi @erp12 have you had the chance to look into whether Python + argparse was the issue? 😁

I have Python installed and argparse is part of the python standard library. I tried running the XGBoost test with multiple versions of python and still got `XGBoostError: XGBoostModel training failed`.

It then occurred to me that I was missing most of the Spark logs (which was critical to the diagnosis of the issue you linked) so I re-ran tests with `log-level` at `DEBUG`. Sorry, I should have thought of that earlier. 🤦 That led me straight to the root cause.

The short answer: I found a MacOS configuration issue on my machine. Nothing related to Geni, and barely related to XGBoost.

The long answer: I found this:

```
DEBUG RabitTracker: Tracker started, with env={}
Tracker started, with env={}
INFO RabitTracker$TrackerProcessLogger: /var/folders/zl/hlg5bvnj1y9753gvjsf0_86r0000gn/T/tracker3668395957512877124.py:400: DeprecationWarning: The 'warn' function is deprecated, use 'warning' instead
INFO RabitTracker$TrackerProcessLogger:   logging.warn('gethostbyname(socket.getfqdn()) failed... trying on hostname()')
INFO RabitTracker$TrackerProcessLogger: 2020-09-30 18:23:00,629 WARNING gethostbyname(socket.getfqdn()) failed... trying on hostname()
INFO RabitTracker$TrackerProcessLogger: Traceback (most recent call last):
INFO RabitTracker$TrackerProcessLogger:   File "/var/folders/zl/hlg5bvnj1y9753gvjsf0_86r0000gn/T/tracker3668395957512877124.py", line 398, in get_host_ip
INFO RabitTracker$TrackerProcessLogger:     hostIP = socket.gethostbyname(socket.getfqdn())
INFO RabitTracker$TrackerProcessLogger: socket.gaierror: [Errno 8] nodename nor servname provided, or not known
INFO RabitTracker$TrackerProcessLogger: 
INFO RabitTracker$TrackerProcessLogger: During handling of the above exception, another exception occurred:
INFO RabitTracker$TrackerProcessLogger: 
INFO RabitTracker$TrackerProcessLogger: Traceback (most recent call last):
INFO RabitTracker$TrackerProcessLogger:   File "/var/folders/zl/hlg5bvnj1y9753gvjsf0_86r0000gn/T/tracker3668395957512877124.py", line 487, in <module>
INFO RabitTracker$TrackerProcessLogger:     main()
INFO RabitTracker$TrackerProcessLogger:   File "/var/folders/zl/hlg5bvnj1y9753gvjsf0_86r0000gn/T/tracker3668395957512877124.py", line 482, in main
INFO RabitTracker$TrackerProcessLogger:     start_rabit_tracker(args)
INFO RabitTracker$TrackerProcessLogger:   File "/var/folders/zl/hlg5bvnj1y9753gvjsf0_86r0000gn/T/tracker3668395957512877124.py", line 444, in start_rabit_tracker
INFO RabitTracker$TrackerProcessLogger:     rabit = RabitTracker(hostIP=get_host_ip(args.host_ip), nslave=args.num_workers)
INFO RabitTracker$TrackerProcessLogger:   File "/var/folders/zl/hlg5bvnj1y9753gvjsf0_86r0000gn/T/tracker3668395957512877124.py", line 401, in get_host_ip
INFO RabitTracker$TrackerProcessLogger:     hostIP = socket.gethostbyname(socket.gethostname())
INFO RabitTracker$TrackerProcessLogger: socket.gaierror: [Errno 8] nodename nor servname provided, or not known
INFO RabitTracker$TrackerProcessLogger: Tracker Process ends with exit code 1
```

So the RabitTracker is starting, but failing to acquire a hostname... This immediately triggered memories of hostname issues that have arisen across the various MacOS versions. After some searching, this SO post seems to sum up the problem pretty well: https://stackoverflow.com/questions/50653103/socket-gethostname-returning-wrong-host-name

In case others come across this issue, the fix was as simple as `sudo scutil --set HostName my-host-name` where `my-host-name` is what can be found in `/etc/hosts`.

@anthony-khong I'll leave it up to you if you would add anything to the docs. I think a note in the contributing guide on how to run tests with different log levels might be helpful.

**Comment by erp12** [comment]
I'll close this issue. Thanks for helping me get setup! Now that I have some familiarity, I hope to be a helpful member of the community. Having a Clojure Spark SQL API is a game changer!

**Comment by anthony-khong** [comment]
> @anthony-khong I'll leave it up to you if you would add anything to the docs. I think a note in the contributing guide on how to run tests with different log levels might be helpful.

I believe I made the default log level to be warning. I'll definitely add this to the contributing guide.

I'm glad you found the problem! Thank you so much for confirming the cause of the issue!
