### ISSUE TITLE
Spark UI has css errors

### ISSUE THREAD

**Issue by behrica** [zero-one-group/geni#231]
![image](https://user-images.githubusercontent.com/127361/95101851-f2e84680-0732-11eb-9594-e3b10d5e8c0c.png)

20/10/05 17:44:56 WARN HttpChannel: /static/spark-logo-77x50px-hd.png
java.lang.NoSuchMethodError: 'boolean javax.servlet.http.HttpServletRequest.isAsyncSupported()'
	at org.sparkproject.jetty.server.ResourceService.sendData(ResourceService.java:697)
	at org.sparkproject.jetty.server.ResourceService.doGet(ResourceService.java:294)
	at org.sparkproject.jetty.servlet.DefaultServlet.doGet(DefaultServlet.java:457)

I saw some reports on this somewhere else, and it is about conflicting servlet implementations.
I got rid of it remove "reply", for example.

**Comment by anthony-khong** [comment]
Hi @behrica, thank you for the issue. I'll try to replicate it and address it in the coming days.

**Comment by behrica** [comment]
This solves it for me:

```clojure
    [reply "0.4.4"
          :exclusions [javax.servlet/servlet-api]]
```

**Comment by anthony-khong** [comment]
Hi @behrica, I made the exclusion, and I believe the issue was auto closed. Would that be okay?
