### ISSUE TITLE
Add common style guide to format the code so that we could share.

### ISSUE THREAD

**Issue by agilecreativity** [zero-one-group/geni#252]
Hi @anthony-khong 

I would love for the project to have common style guide so that everyone are on the same page. 

e.g. We could be using different IDE to edit the code, but then in the end we can all agree on one common style to avoid stepping on each other.
The tools like [cljfmt](https://github.com/weavejester/cljfmt) make this very simple.

It works very well with Leiningen project via the following plugin

```
:plugins [[lein-cljfmt "0.7.0"]]
```
Can can be run very simple via the two command:

```
lein cljfmt check
```
It can fix using something like

```
lein cljfmt fix
```

This can be run as part of the build/cicd check.
If you are ok with it then I can create a PR and you can take a look. 
For now I don't want to do this unless you are ok with it.

Thanks

**Comment by anthony-khong** [comment]
Hi Burin, I think this is a good idea! Let’s do it! 👍👍

Maybe just the formatting check, without the auto fix? Just like how lein-ancient is currently used.

And may I suggest that we incrementally format a small number of files first? Say, just, the RDD namespace to begin with, and tweak the cljfmt config to something we can all agree with. What do you think?

**Comment by agilecreativity** [comment]
Hi Anthony,

Definitely we can do that.
I created the simple PR to show you with default rules (plus some custom rules to make it work with midje) 
You can take a quick look here.

[Sample PR with the result of running the tools against different directory](https://github.com/zero-one-group/geni/pull/254)

This is intended for you to do a quick review and to see if you are ok with the result. If you like to change anythings then we can start to customize the rules and only merge the PR when you are happy with the result.

Please provide some comment to what rules you like to tweak and annotate that in code so I can try to tweak them.

If you are ok, we can definitely start with the RDD namespace.

**Comment by anthony-khong** [comment]
Hi Burin, what do you think about adding a CI job for `lein-cljfmt` for directories that have been reformatted? Just to avoid regression 😄

**Comment by anthony-khong** [comment]
Hi @agilecreativity , I thought I'd let you know that I've started working on this. I've also added the CI job for the check. See this PR: https://github.com/zero-one-group/geni/pull/276

I thought, just to be conservative, we do a big chunk every week, and I expect to be done in a couple of weeks' time. I hope that's okay!

**Comment by agilecreativity** [comment]
I was busy for a bit but yes having this as part of ci build make perfect sense to me.

**Comment by agilecreativity** [comment]
This is no longer an issue as #276 is already merged.
So happy to close this. 
Thanks for great library.

**Comment by anthony-khong** [comment]
FYI, core and some other test namespaces are not normalised yet, but it'll be done next week!
